smaz.lo: /home/wangzhenhao/php_dev/php-5.3.27/ext/smaz/smaz.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wangzhenhao/php_dev/php-5.3.27/ext/smaz $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wangzhenhao/php_dev/php-5.3.27/ext/smaz/smaz.c -o smaz.lo 
$(phplibdir)/smaz.la: ./smaz.la
	$(LIBTOOL) --mode=install cp ./smaz.la $(phplibdir)

./smaz.la: $(shared_objects_smaz) $(SMAZ_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_smaz) $(SMAZ_SHARED_LIBADD)

